[package]
name = "steam_crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
quick-xml = "0.27.1"
scraper = "0.14.0"
ureq = "2.6.2"
url = "2.3.1"
